repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --config-file mypy.ini aerospike_provider/
        language: system
        types: [python]
        require_serial: true
        verbose: true
        pass_filenames: false
