repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-merge-conflict

# TODO: fix mypy issues
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.8.0'
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       language: system
  #       types: [python]
  #       require_serial: true
  #       verbose: true
  #       pass_filenames: false
