name: Pull request

on:
  workflow_dispatch:
  pull_request:
    branches: master

jobs:
#   lint-pr-title:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Lint pull request title
#         uses: jef/conventional-commits-pr-action@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}


  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python (3.8)
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

      - name: Run unit tests
        run: |
          python -m unittest -v
